const routeConfig = {
	'audit_logs': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'brands': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'cart_items': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'carts': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'categories': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'customers': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'import_invoice_details': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'import_invoices': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'inventory': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'order_details': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'order_promotions': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'orders': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'payment_methods': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'product_images': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'products': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'promotions': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'refresh_tokens': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'reviews': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'shipping_methods': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'suppliers': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'transactions': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'users': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
	'warehouses': {
		getAll: 'public',
		getById: 'public',
		insert: 'admin',
		update: 'admin',
		delete: 'admin',
	},
};
export default routeConfig;
